### PR TITLE
Feature/include test sdist

### PR DESCRIPTION
**Pull request by meeuw**
## Description
Include tests (and more missing files) in sdist

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by tsroten** [comment]
Thanks! I like the idea of including tests and other files in `sdist`.

Any particular reason for the change from `tests` to `test`? It seems like `tests` a fine [way](https://docs.pytest.org/en/latest/goodpractices.html) [of](https://github.com/django/django) [doing](https://github.com/pallets/flask) [it](https://github.com/pallets/click).

**Comment by meeuw** [comment]
Oh I only explained it in de commit message:
https://github.com/dbcli/mycli/pull/411/commits/60b08f1b29f63149cd7a90c6b772517d33598789

Anything that looks like a test script: test/test*.py (currently, the
Distutils don't do anything with test scripts except include them in
source distributions, but in the future there will be a standard for
testing Python module distributions)

https://docs.python.org/3/distutils/sourcedist.html

**Comment by tsroten** [comment]
Sounds good to me :) I'll review and merge later today.

**Comment by tsroten** [comment]
@meeuw Looks like some pep8radius errors.

**Comment by meeuw** [comment]
Allright, I've fixed the pep8 code style violations

**Pull request merged**
