### PR TITLE
Switch from pycryptodome to cryptography.

### PR DESCRIPTION
**Pull request by tsroten**
## Description
This pull request switches mycli from using [pycryptodome](https://github.com/Legrandin/pycryptodome) to using [cryptography](https://github.com/pyca/cryptography).

pycryptodome cannot be installed alongside of pycrypto, which is a problem from some Linux distributions like Fedora. By using cryptography, which has a totally different API, we should not run into that problem. Plus, cryptography appears to be better maintained and better tested.

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by tsroten** [comment]
@meeuw Can you confirm that cryptography >= 1.0.0 will be acceptable for the Fedora package?

**Comment by tsroten** [comment]
Hmm, I didn't even notice that pycryptodome has a non-conflicting installation, too:
```
pip install pycryptodomex
```
> In this case, all modules are installed under the Cryptodome package. PyCrypto and PyCryptodome can coexist.

**Comment by amjith** [comment]
@tsroten I'm not sure if I'm the best candidate for testing this. I don't use the my_login file to store my credentials. So I'm not sure how to test this change and make sure nothing is broken.

**Comment by tsroten** [comment]
@amjith No problem :)

@meeuw or @j-bennet Are either of you familiar with the login path feature and have time to review/test this?

**Comment by meeuw** [comment]
Fedora has cryptography 1.5.3, I don't use my_login file either, I think it uses this:
https://dev.mysql.com/doc/mysql-utilities/1.5/en/mysql-utils-intro-connspec-mylogin.cnf.html

**Comment by tsroten** [comment]
Yes, that's right.

```
$ mysql_config_editor set --login-path=test --host=localhost --user=user -p
Enter password:
$ mycli --login-path=test
```

**Comment by meeuw** [comment]
I'll try to create a unittest for this

**Comment by meeuw** [comment]
There are already unittests covering it :smile:

**Comment by tsroten** [comment]
Yep :) I think if we could just get someone to review the code changes and test it out from the end user perspective, we'll be good.

**Comment by amjith** [comment]
Someone sent a request to start using pycryptoDome, can we ask that person
to test-drive this per request?

**Comment by tsroten** [comment]
@mgorny Thanks for [your pull request](https://github.com/dbcli/mycli/pull/358) a little while ago to switch mycli to pycryptodome! We're looking at switching to [cryptography](https://pypi.python.org/pypi/cryptography), which seems a bit more active, has wheels for macOS (in addition to Windows), and looks very well tested.

If you use the encrypted login path feature of mycli, would you be willing to give this branch a test run?

**Comment by mgorny** [comment]
Thanks but I don't really use that — I've merely tried to get rid of one dependency on my system, and focused on the test suite.

**Comment by johnksterling** [comment]
I can probably try it out.

John

**Comment by tsroten** [comment]
Thanks @johnksterling!

No problem, @mgorny, thanks for letting us know!

**Comment by tsroten** [comment]
@johnksterling Any luck?

**Comment by amjith** [comment]
There are tests that cover this and I trust @tsroten to have done a good job testing this. I'm going to merge this PR.

**Pull request merged**
