### PR TITLE
implemented DELIMITER command

### PR DESCRIPTION
**Pull request by pasenor**
## Description
#383 
DELIMITER command to switch the default delimiter `;` to something else. Copied the behavior from the standard mysql shell. 

Splitting lines is based on a [suggestion](https://gist.github.com/srittau/01282d7e306ae5f73c601752f2503fa6) by @srittau as a temporary workaround until custom delimiters get into the sqlparse library

One limitation is that delimiter cannot be used in a favorite query, for example if you save

    \fs foo delimiter $ select 1 $ select 2 delimiter ;

then `\f foo` will result in a syntax error, although a user may actually want to save such a query, e.g. to do some work on stored procedures. I can imagine refactoring favorite queries so that they are executed with `SQLExecute`, then all special commands will be available, but I'm not sure if it's worth the trouble.
UPD: ah, I see Thomas has been doing some work towards special commands is favorite queries in #600 so it's probably better to handle there.

Another concern is that I have changed the API of  `_multiline_exception` (it now accepts the delimiter argument), which is one more difference from pgcli and the rest of the dbcli tools.

And generally, though having delimiter switching may be useful to people accustomed to the default mysql shell, it's primary purpose is to deal with stored procedures. Maybe it would be more straightforward to implement a simple call stack, so we can track BEGIN - END statements directly? 

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by meeuw** [comment]
1. I think DELIMITER should be implemented in a class in mycli.packages.special and the delimiter should be stored there instead of passing it around though a lot of functions
1. What is the actual use case for having a delimiter other than `;` ?

Nice work though, it seems pretty thorough!

**Comment by amjith** [comment]
> What is the actual use case for having a delimiter other than ; ?

The delimiter is changed from the default (;) when you want to create functions that have semi-colons in them. 

This stackoverflow answer does a better job of explaining it. 

https://stackoverflow.com/a/10259528

**Comment by amjith** [comment]
> I think DELIMITER should be implemented in a class in mycli.packages.special and the delimiter should be stored there instead of passing it around though a lot of functions

@pasenor Do you want to take a stab at implementing it as part of the special commands package? 

When I try out the feature I see `DELIMITER` listed twice in the completion menu. This is because it is listed as a keyword in sqlcompleter.py and also as a special command. You can remove the entry from the keyword in sqlcompleter.py file.

**Comment by pasenor** [comment]
>     1. I think DELIMITER should be implemented in a class in mycli.packages.special and the delimiter should be stored there instead of passing it around though a lot of functions

Makes sense, but we still need to somehow let the `is_multiline` function know about the new delimiter. I'll look into it, probably swapping the `prompt_app.multiline` could be an option.

**Comment by pasenor** [comment]
> What is the actual use case for having a delimiter other than ; ?

As @amjith said, the only use case is declaring stored procedures with `;` in them.
In fact, I feel it's an ugly solution, and what we need instead is a proper scoping based on `BEGIN ... END`, like what `psql` does.  But a lot of scripts tailored for mysql  already use `DELIMITER` (I too have a couple of them), and it would be nice if mycli could run them.

**Comment by meeuw** [comment]
mmm, I never used stored procedures in mysql, sounds like a valid use case...

**Comment by amjith** [comment]
This works great! I like how thorough the tests are done for this feature. :1st_place_medal:

**Comment by meeuw** [comment]
nicely done @pasenor !

**Pull request merged**
