### PR TITLE
Backport context managers in pymysql from 0.6.6 to 0.6.2

### PR DESCRIPTION
**Pull request by amjith**

### CODE REVIEW

**Comment by amjith** [comment]
@tsroten I've created a PR based on your branch, so we can have a discussion. The changes look good.

I'm currently testing it.

**Comment by amjith** [comment]
Works well. I've tested it on 0.6.2, 0.6.4 and 0.6.6. Everything is working fine. I think this is good to merge.

If you have any more changes, please let me know. If I don't hear back, I'll assume everything is good and merge it in tomorrow. 

Thanks for making this change. 

:mushroom:

**Comment by tsroten** [comment]
Do you think 0.6.4 should be added to `.travis.yml`?

**Comment by amjith** [comment]
No need to add 0.6.4. I was just being extra cautious. :)

**Pull request merged**
