### PR TITLE
parseutils: Consider update-statement without where-clause as destruc…

### PR DESCRIPTION
**Pull request by kwuenschel**
## Description
Consider `update`-statements without `where`-clause as destructive-queries.

Related issue: https://github.com/dbcli/mycli/issues/728

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by pasenor** [comment]
Nice! While you're at it, will you consider adding `DELETE` without `WHERE`to the new check as well?

**Comment by kwuenschel** [comment]
Thanks for pointing that out, I wasn't thinking about this case. This could be a bit more difficult, I'll take a look at it.

**Comment by pasenor** [comment]
@kwuenschel are you working on this? Otherwise let's merge this PR and open a separate issue about multi-column updates.

**Comment by pasenor** [comment]
Merging this PR, thanks a lot for the fix! The multiple-table issue will be addressed in #791.

**Pull request merged**
