### PR TITLE
I wish you can add the "ssh forward" in this tools , although there are some bugs that I do not find. 

### PR DESCRIPTION
**Pull request by iubuntu**
## Checklist

- [ ] I've added this contribution to the `changelog.md`.
- [ ] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by tsroten** [comment]
@iubuntu Hello! Thanks for your work on this 😄 

It looks like this pull request needs a few things to make it work well with mycli:
1. The README is updated for a different project. Can you undo your changes to it?
2. It looks like there are a few `print()` statements that probably shouldn't be there. I don't think we need to output anything to the user since they'll know it's connecting over SSH because they will have passed in the necessary command-line arguments.
3. The `setup.py` file needs to be updated with the new dependencies.

Here are a few ideas that might make the user's experience better:
1. The `--jump` option seems like it isn't very self-explanatory. Maybe simply `--ssh` would work?
2. It would be nice to include the ability to pass in the SSH password.
3. Can we make the command-line options use hypens so they're easier to read? E.g. `--ssh-key`, `--ssh-user`, etc.

**Comment by tsroten** [comment]
This relates to https://github.com/dbcli/mycli/issues/18

**Comment by meeuw** [comment]
@iubuntu I've created https://github.com/dbcli/mycli/pull/634 which does the same as you're trying to achieve in this PR. Could you please test it (you can install it using `pip install git+http://github.com/dbcli/mycli@feature/ssh_transport`).

**Comment by iubuntu** [comment]
@tsroten  Thanks for your to review the codes and give me suggestions.
I have changed my code : 
 1.  The `README`  is undone. 
 2.  I removed few `print()`  . 
 3.  I added the `sshtunnel` in `setup.py` file.

In addition, 

1.  the `--jump` option is renamed to `--ssh`
2. add `ssh-password` option to support password
3. rename `sshport` `sshusername` `sshkey` to `ssh_port` `ssh_user` `ssh_key`


I am not immediately to replay your comment,   because I  found sone problems . 
 1.   I try to add `connect_uri(` but is not work
 2.  I try to add options in configure files.

**Comment by iubuntu** [comment]
@meeuw  Thanks , I viewed your code, It is super better and clear than that I wrote . 

After I tested the code, I find a small error  in sqlexecute.py:`SQLExecute.connect`.   when I  set that  `--ssh-port` is not 22,  the `ssh_port`  in function named `connection` is `22`.

**Comment by meeuw** [comment]
You're right iubuntu! I've fixed it, thanks for reporting!

**Comment by tsroten** [comment]
@iubuntu Thanks again for your pull request! We've already merged #634, so I'm going to close this.

**Pull request closed without merging**
