### PR TITLE
Fixes editor bug with prompt_toolkit 1.0.13.

### PR DESCRIPTION
**Pull request by j-bennet**
## Description

Fix for https://github.com/dbcli/mycli/issues/377.

Ported from https://github.com/dbcli/pgcli/pull/670.

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [X] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by meeuw** [comment]
Do we need backward compatibility for an older version of prompt_toolkit? Because this fix doesn't work with prompt_toolkit==1.0.9 (which is the current version for Fedora).

**Comment by j-bennet** [comment]
Hmm. Or, the other option would be to bump minimal requirement of prompt_toolkit. Any specific reason we're keeping it at 1.0.9?

**Comment by amjith** [comment]
Whatever solution we pick needs to work on both pgcli and mycli. Because we have users who use both and they are not able to install pgcli and mycli simultaneously because we've required conflicting prompt-toolkit versions in the past.

**Comment by j-bennet** [comment]
Agree. I think we still have the mismatch in master, pgcli specifies 1.0.0 as the lowest, and mycli has 1.0.9.

**Comment by meeuw** [comment]
> Any specific reason we're keeping it at 1.0.9?
Fedora 25 provides a packaged version of mycli which uses prompt_toolkit 1.0.9 but I've investigated and all other packages depending on prompt_toolkit require prompt_toolkit<1.1.0 or no specific version so that will be their own fault if it breaks. I'm all in for a new version of prompt_toolkit.

**Comment by tsroten** [comment]
@j-bennet This looks good. Since it sounds like this fix does not work with <1.0.10 (right?), then we need to bump the `setup.py` prompt toolkit, which is currently at 1.0.0 through 1.1.0.

**Comment by tsroten** [comment]
Oops, sorry about closing that!

**Comment by j-bennet** [comment]
I've been swamped the last few days, but this is exactly what I'm going to do: bump prompt-toolkit to 1.0.10 in this PR and merge.

**Pull request merged**
