### PR TITLE
Fix favorites completion

### PR DESCRIPTION
**Pull request by amjith**
## Description
Addresses #845. 

The FavoriteQueries implementation now closesly resembles pgcli's NamedQueries implementation. 

Updated changelog.

### CODE REVIEW

**Comment by amjith** [comment]
Yes. It did fix the problem. The reason was the global variable was getting created multiple times when the module was imported in different files with different names. Eg: import iocommands.favoritequeries vs from .packages import special. 

So at completion time the global variable wasn't populated correctly. With the singleton there is only one instance and it works as expected.

**Comment by j-bennet** [comment]
Love it. ❤️ Very nice catch.

**Comment by laixintao** [comment]
Hi @amjith I am confused by

>  Eg: import iocommands.favoritequeries vs from .packages import special.

Why would anyone import the save class from different files in the first place? :)

**Comment by amjith** [comment]
@laixintao We weren't importing the save class. We were importing the favoritequeries from main.py to be able to populate the favorite queries from the config file. Then we import favoritequeries from the sqlcompleter to be able to show completion suggestions. 

But merely importing the module has the side effect of instantiating a new FavoritQueries object. So they were both dealing with different objects. That's why I made it a singleton in this PR.

**Comment by laixintao** [comment]
I Get it. 👍

**Pull request merged**
