### PR TITLE
Unicode output to click for Python 2.7

### PR DESCRIPTION
**Pull request by meeuw**
## Description
Unicode output to click for Python 2.7 (fixes failing behave tests in master)

I'm not sure if this is the right way for Python 2/3 compatibility

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by tsroten** [comment]
Hmm I wonder why `output` is not already Unicode. Doesn't CLI Helpers return Unicode?

**Comment by meeuw** [comment]
Hmm good point, I'll try to figure it out

**Comment by tsroten** [comment]
Thanks! My concern is that we *should* be using Unicode internally, and in the PR we are decoding without an explicit encoding.

**Comment by meeuw** [comment]
Yep, found it: https://github.com/dbcli/cli_helpers/pull/32 you're the best @tsroten :smile:

**Comment by tsroten** [comment]
@meeuw  Nice job!!!

**Pull request closed without merging**
