### PR TITLE
Handle invalid port validation exception.

### PR DESCRIPTION
**Pull request by amjith**
@tsroten You have a valid point. I've handled the ValueError in this PR. We can fix this in our next release since this is not an urgent requirement.

### CODE REVIEW

**Comment by loslots** [comment]
I believe this 3306 # is from my phone I was on in the Early AM hoping to get help fixing my phone I just had turn on and like all my last 6+ phones it seems to be connected somehow to the rest. My SigvothervI believe has done this and uses them to 1 c what I do and 2 go to Chat/Dating or maybe worse (pornography)  its on my yahoo Acct as well so if I can help please let me know and maybe you might put it up on the priority list a bit please. I'm crushed to the core at what I seen today and have been seeing pieces of for going on 2 yrs.Please help and thank you

**Comment by tsroten** [comment]
@amjith Nice!

Do you think `Invalid port number: '3306a'` might be more helpful than `Invalid port number. invalid literal for int() with base 10: '3306a'`?

**Comment by amjith** [comment]
I couldn't find a good way extract out just the port number. If you can
think of a good way to do it, please feel free to edit.

**Comment by amjith** [comment]
Thanks for making it user friendly.

 :sunflower:

**Pull request merged**
