### PR TITLE
Add alias dsn

### PR DESCRIPTION
**Pull request by fraoustin**
## Description
add support alias dsn.
Save your alias dsn in myclirc in section alias_dsn
You can use alias by option "-d" : mycli -d my_alias_dsn

Same usage than pgcli

## Checklist
- [ ] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by tsroten** [comment]
Hi @fraoustin! Thanks for the pull request!!

I'm curious if you've used the existing feature in mycli that handles storing server information (like the MySQL client does) - http://www.mycli.net/loginpath

I didn't know if this DSN feature was added because there was an issue with the login path feature, or if there is a use case it doesn't handle well.

Thanks!

**Comment by fraoustin** [comment]
Hi i don't use this feature http://www.mycli.net/loginpath because on my computer I do not have the mysql_config_editor tool. 
I tested this feature and it is ok but my pull resquest does not have same aim.

I have a question: Travis build failed, how i change my code? i generate a new pull request with correction? (just a problem of synthax)

Happy christmas

**Comment by fraoustin** [comment]
I changed blank in main.py

**Comment by tsroten** [comment]
@fraoustin Thanks for the updates to pass the tests. I like how simple the DSN approach is for users. Like you said, they don't have to have mysql config editor installed. Plus, this means the experience across pgcli and mycli is the same.

Great work 👍 !

**Comment by tsroten** [comment]
@fraoustin Thanks again! This was just released in mycli version 1.16.0. I also added some documentation to mycli.net about this feature: http://www.mycli.net/loginpath#dsn

**Pull request merged**
