### PR TITLE
Echo status line

### PR DESCRIPTION
**Pull request by tsroten**
## Description

This calls `mycli.echo` for outputting the status line. This means the status line won't end up in the pager, once file, or tee file.

See https://github.com/dbcli/mycli/issues/455 for more information.

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by tsroten** [comment]
@meeuw -- I'm having trouble getting this to work with pexpect/behave. Can you lend a hand?

**Comment by meeuw** [comment]
sure, pexpect/behave was using exactly this functionality 😄 

`expect_pager` should be changed to `expect_exact` for all status lines and ```
 wrappers.expect_exact(
        context, context.conf['pager_boundary'] + '\r\n', timeout=5)
```

should be removed in `crud_database.py`.

Still would it be nice if we could recognize the status line boundaries some other way in pexpect/behave, maybe be using some fancy formatting?

**Comment by tsroten** [comment]
@meeuw Thanks! I just pushed those changes you mentioned, but it's having trouble recognizing the status lines with `expect_exact()`.

**Comment by meeuw** [comment]
Ah, it seems there's no `\n` for `click.echo` and the `\r` is prefixed with some escape codes. If you remove `\r\n` from the expect_exact lines it only seems to fail on `iocommands` -- I'm working on that.

**Comment by tsroten** [comment]
@meeuw Thanks!! If you think this is ready, feel free to merge it.

**Pull request merged**
