### PR TITLE
Fix/use after create delete

### PR DESCRIPTION
**Pull request by SukiCZ**
## Description
Is not evaluating `is_dropping_database` as `True` if `CREATE` statement follows for same db

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there). ( :two_hearts: )

### CODE REVIEW

**Comment by amjith** [comment]
Hi @SukiCZ. Thank you for the PR. Can you give me a little bit more context around why this change is necessary? Is there a use case that you encountered which resulted this change? 

The idea behind this check is to ensure that we reinitialize the connection and refresh our completions when we encounter a DROP statement because that is a DDL statement that requires a completion refresh. With the change you're suggesting it could invalidate that refresh trigger. 

So I'm trying to understand if there is a specific problem you're trying to solve with this change.

**Comment by pasenor** [comment]
Ah, @amjith I see what you mean. @SukiCZ here is a query that would break everything after your change:

    DROP DATABASE foobar; CREATE DATABASE foobar; DROP DATABASE foobar;

**Comment by SukiCZ** [comment]
Hi @pasenor , @amjith :wave:
Thanks for your review / time :timer_clock:
Not that I have any personal use-case for this but I've noticed opened issue referencing this. I thought it might be a easy way to contribute. (Late HacktoberFest :smile: )
Maybe I was too rush thinking about this - maybe we could extend `is_dropping_database` to enforce re-initialization of new connection, yet keep using the same one - or maybe to open discussion on this topic.

`is_dropping_database('DROP DATABASE foo; CREATE DATABASE foo; DROP DATABASE foo', 'foo')` is evaluated as `True`.

What's your thoughts? :thinking: 
Cheers :+1:

**Comment by amjith** [comment]
Do you have a reference to the issue that you were trying to address with this PR? We can perhaps find an alternative solution.

**Comment by SukiCZ** [comment]
sure. should be #756

**Comment by amjith** [comment]
@tsroten Would you mind reviewing this PR? 

I know you had some experience with a bug fix related to drop statement.

**Comment by tsroten** [comment]
@SukiCZ Hi! Thanks for this contribution 😄 I'm sorry it's taken me so long to look at it. It looks great to me. I'm going to resolve the conflicts and then merge it.

**Pull request merged**
