### PR TITLE
Feature/keywords

### PR DESCRIPTION
**Pull request by KeatingSmith**
## Description

Add more keywords.

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by meeuw** [comment]
Thanks for this suggestion! Did you intentionally ran Imgbot on /screenshots/tables.png? Could you please add this contribution to changelog.md?

**Comment by KeatingSmith** [comment]
Of course.

**Comment by meeuw** [comment]
Lol, I was referring to the added keywords, not Imgbot. Sorry about that.

**Comment by KeatingSmith** [comment]
Lol, I got get it wrong.:{

**Comment by meeuw** [comment]
thanks a lot!

**Pull request merged**
