### PR TITLE
No connection on use

### PR DESCRIPTION
**Pull request by AngeloLupo**
## Description

Exposed ```pymysql.selectdb``` through sqlexecute
Added error message on ```use``` with no parameters

## Checklist

- [ ] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by meeuw** [comment]
Hey this is nice! This will fix prevent reconnects when you change databases.

There's only some issue that the list of databases will contain duplicate entries when you switch to another database using `use`.
```
mysql root@172.17.0.2:(none)> use mysql                                             
You are now connected to database "mysql" as user "root"
Time: 0.002s
mysql root@172.17.0.2:mysql> use  
                                  _test_db            
                                  _test_db            
                                  information_schema  
                                  information_schema  
                                  mysql               
                                  mysql               
                                  performance_schema                                
```

**Comment by tsroten** [comment]
@AngeloLupo Thanks for your contribution! I'm just leaving a comment to note that this pull request is addressing issue #644.

**Comment by AngeloLupo** [comment]
> Hey this is nice! This will prevent reconnects when you change databases.
> 
> There's only some issue that the list of databases will contain duplicate entries when you switch to another database using `use`.
> 
> ```
> mysql root@172.17.0.2:(none)> use mysql                                             
> You are now connected to database "mysql" as user "root"
> Time: 0.002s
> mysql root@172.17.0.2:mysql> use  
>                                   _test_db            
>                                   _test_db            
>                                   information_schema  
>                                   information_schema  
>                                   mysql               
>                                   mysql               
>                                   performance_schema                                
> ```

Good spot, that should be fixed now!

**Comment by meeuw** [comment]
The current behavior of using `use` without any arguments is to set None as the current database. I'm not sure why this is useful but it seems to be implemented this way on purpose. @amjith do you remember why you did this and do you like to new behavior?

Could you please add your contribution to the changelog? Many thanks!

**Comment by meeuw** [comment]
I just discussed this with @amjith and this feature (use without arguments) doesn't need to exist anymore.

Thanks again, I'm merging this PR!

**Pull request merged**
