### PR TITLE
Display multiple result sets.

### PR DESCRIPTION
**Pull request by tsroten**
## Description

This displays all result sets returned by a query (e.g. stored procedure).

See #387 for more information.

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by j-bennet** [comment]
Looks good and seems to work great! One small thing: it would be nice to have a newline between results sets. For example, I have this procedure that selects from two tables:

```
mysql> delimiter //
mysql> create procedure t1()
    -> begin
    ->   select * from aaa;
    ->   select * from bbb;
    -> end//
```

calling in `mysql`:

```
mysql> call t1();
+------+
| xxx  |
+------+
| boo  |
+------+
1 row in set (0.00 sec)

+------+------+
| id   | name |
+------+------+
|    1 | foo  |
+------+------+
1 row in set (0.00 sec)

Query OK, 0 rows affected (0.00 sec)
```

calling in mycli:

```
mysql root@localhost:test> call t1()
+-------+
| xxx   |
|-------|
| boo   |
+-------+
1 row in set
Time: 0.001s
+------+--------+
|   id | name   |
|------+--------|
|    1 | foo    |
+------+--------+
1 row in set
Time: 0.001s
mysql root@localhost:test>
```

I think an extra newline in between would add readability.

**Comment by meeuw** [comment]
Really nice! The only problem I see is that only one result is outputted for the `\once` command.

**Comment by tsroten** [comment]
@j-bennet @meeuw Thanks for both of those points :) You're definitely right, I'll fix those things.

**Comment by tsroten** [comment]
@j-bennet @meeuw Can you check this again? There should be an extra newline between result sets. And, multiple results should end up in the once file.

**Comment by meeuw** [comment]
:ok_hand: great

**Comment by j-bennet** [comment]
Looks perfect now. 👍

**Pull request merged**
