### PR TITLE
Update build badge

### PR DESCRIPTION
**Pull request by shoma**
To show project popularity if you like.

### CODE REVIEW

**Comment by amjith** [comment]
@shoma Thanks for the PR. That is very kind of you. But showing the download count and PyPI version is not very useful for the user. It's mostly a vanity metric for bragging rights. I don't think that's the impression I was to portray with mycli.

The travis badge is useful, I didn't realize my link to that badge was broken in README.

So I'm going to merge this in, but remove the pypi count badge line. 

Thank you! :fish_cake:

**Comment by shoma** [comment]
@amjith 
I think the download count is not for vanity, it is for reliability of the project, but I'm OK you think so.
`mycli` is great tool for me,  I'm lovin' :heart: Thank you.

**Comment by amjith** [comment]
I'm very happy that you love the project. I understand that it can be perceived as a metric of reliability. But somehow displaying the download count doesn't seem right to me. Thanks for understanding.

**Comment by tsroten** [comment]
Plus, GitHub has a built-in metric for popularity -- stars in the top right corner.

**Pull request merged**
