### PR TITLE
Fix mysql4 version comment retrieval

### LINKED ISSUE #502: mycli remote connect fail  ，system is macOS，local is OK
log：
image

image

remote mysql version：

image

can  you help me？

### PR DESCRIPTION
**Pull request by fpietka**
## Description
The query fetching version comment was failing on MySQL 4.
Fix #502 

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by fpietka** [comment]
FYI, I used tommi2day/mysql4 docker image to test it.

**Comment by meeuw** [comment]
@fpietka thanks for working on this; as a reminder, I get an error with python 2.7/mysql 4, could you please have a look? Maybe use `.encode('utf8')` instead of `str(..., 'utf8')`.

**Comment by fpietka** [comment]
@meeuw thanks for the reminder. I tested it on python2/3 with mysql4 only though.

**Comment by meeuw** [comment]
:+1: works! Thanks a lot. Only the `\s` (or `status`) command seems to return an error, Do you think this can/should be solved in this PR?

**Comment by fpietka** [comment]
I am not sure how, there is no `GLOBAL` in mysql4. I could try to use `SHOW STATUS` and `SHOW VARIABLES` as fallback, but I'm not sure if it is the same.

**Comment by fpietka** [comment]
I'm trying to get something, but it seems we're missing some keys in status.

**Comment by fpietka** [comment]
Ok, I came with a workaround. Let me know what do you think about it.

**Comment by j-bennet** [comment]
@fpietka It looks like your tests are failing because of pep8 checks. Run `pep8radius master -i --docformatter` to fix that.

**Comment by fpietka** [comment]
I switched to pyenv to make my virtualenv, but it doesn't use system packages (hence I wasn't linting anymore on vim...)

**Comment by meeuw** [comment]
Works like a charm! Thanks @fpietka!

**Pull request merged**
