### PR TITLE
Update README with new auto-vertical-output option

### PR DESCRIPTION
**Pull request by mdsrosa**
I've updated the `Usage` section in README with the new _awesome_ option. :smile: 

Reviewer: @amjith :)

### CODE REVIEW

**Comment by amjith** [comment]
Looks good. :+1:

**Comment by mdsrosa** [comment]
@amjith I was thinking about adding more stuff in the `Features` section. Maybe. Do you think we need to add more updates to the README?

**Comment by amjith** [comment]
It doesn't hurt to add more. If you have the time, go for it. I'd also like to update this page http://mycli.net/config with the latest contents of our `myclirc` file. 

You can do that by updating this file: https://github.com/dbcli/mycli.net/blob/master/content/pages/config.md

**Comment by mdsrosa** [comment]
Yes, of course. I'll do a list of mycli features and update the README in another PR.

About the config page that's easy. I'm opening a PR right now to mycli.net. :-)

**Comment by mdsrosa** [comment]
@amjith I decided to keep this PR instead of opening a new one. So I've updated the PR with some new features added to the `Features` section in README. :smile:

**Comment by amjith** [comment]
Looks nice!

Thank you!

:cactus:

**Pull request merged**
