### PR TITLE
Resolves issue #1038

### PR DESCRIPTION
**Pull request by morgan-greywolf**
## Checklist

- [ ] I've added this contribution to the `changelog.md`.
- [ ] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by rolandwalker** [comment]
Hello!  Thank you so much!  Checking…

**Comment by rolandwalker** [comment]
Would you be willing to fix the tests and add to the changelog as @Arvind2222 has showed in #1040 ?

Or should I migrate to the other PR?

**Comment by Arvind2222** [comment]
@rolandwalker If possible could you please enable the pipeline run for https://github.com/dbcli/mycli/pull/1040
I think the changes then can be tested ?

**Comment by rolandwalker** [comment]
Handled in #1042.

**Pull request closed without merging**
