### PR TITLE
Add test for handling bug with sqlparse 0.2.2.

### PR DESCRIPTION
**Pull request by meeuw**
## Description
sqlparse==0.2.2 gives:
AttributeError: 'NoneType' object has no attribute 'normalized'

Added a regression test to test_completion_engine.py

## Checklist

- [x] I've added this contribution to the `changelog.md`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by tsroten** [comment]
Nice catch!

sqlparse 0.2.3 has been out less than two months. I'm wondering about how this will affect various Linux distributions. What do you think?

**Comment by meeuw** [comment]
That a valid point, I'll have a look at the compatibility code which I've removed (see if it can catch this error).

I think Linux distributions will follow (because not much project depend on a specific version of sqlparse)

**Comment by meeuw** [comment]
I've reverted my commit to remove the temporary hack and added some code to make pytest happy

**Comment by tsroten** [comment]
@meeuw Looking good! Looks like the changelog edit is still in there

**Comment by tsroten** [comment]
@meeuw Thanks for working out the tests on this one :)

**Pull request merged**
