### PR TITLE
Use the multiline continuation char from config.

### PR DESCRIPTION
**Pull request by amjith**
## Description
Addresses #839

### CODE REVIEW

**Comment by pasenor** [comment]
hmm, I'm getting this, both with multiline on and off :thinking: 
image

**Comment by pasenor** [comment]
Ah, do you mean allowing the user to set `""` for prompt_continuation? That one works as expected once I've seen the above picture, but a priori I probably wouldn't expect it to repeat.

**Comment by amjith** [comment]
You're right. I didn't think about the existing config files for all the users. 

Let me think about this a bit more. I'll amend this PR.

**Comment by amjith** [comment]
I have updated this PR. 
image

**Comment by pasenor** [comment]
Looks good, merging

**Pull request merged**
