### PR TITLE
Adds nopager command and skip-pager config option.

### PR DESCRIPTION
**Pull request by tsroten**
This pull request adds support for the `nopager` and `\n` commands (that mimic MySQL's client). Issuing either of those commands will disable the pager until the pager is set again with the `pager` or `\P` command.

It also adds support for the `skip-pager` config option in user's `.my.cnf` file. Like expected, this must be specified in the `[client]` section of the file. If `skip-pager` is set, regardless of the value, the pager will be disabled. This mimics MySQL's behavior.

### CODE REVIEW

**Comment by tsroten** [comment]
By the way, this PR is to address #218.

**Comment by amjith** [comment]
:octocat:

**Comment by horosgrisa** [comment]
@amjith Can you add posibility to set own pager?

**Comment by timfeirg** [comment]
is it possible to add nopager into `.myclirc` config files? I didn't see any lines related to pager in http://mycli.net/config @tsroten

**Comment by tsroten** [comment]
@timfeirg Hello! We are planning on adding those options to the myclirc file (when we rework our config-related code). For now, you can it to the file .my.cnf:
```
[client]
skip-pager=on
```

That will turn the pager off. I hope that helps!

**Pull request merged**
