### PR TITLE
Fixes #202 and #284

### LINKED ISSUE #202: Boring Connection reset.
Again, me     :)

vipcenter> select \* from member;
Connection reset. Reconnect (Y/n): Y
Reconnected!
Try the command again.

Why my connection is always be reset, should I change some mysql setting?

### PR DESCRIPTION
**Pull request by jialongl**

### CODE REVIEW

**Comment by amjith** [comment]
@jialongl Thanks for the PR. I'm checking it out now.

**Comment by amjith** [comment]
This works great. Thank you for the contribution. I'm still reading through the code to make sure it's all good. I'll merge it in once I'm satisfied. It should be later today.

**Comment by jialongl** [comment]
Thanks.

In summary, the commit
- moved a big code block into a function `one_iteration` (thus changing some `continue`s to `returns`) with one single argument `document` (defaults to `None`);
- moved the initilizations of `document` var into an `if` block when `document` is `None`.
- calls `one_iteration(document)` (recursion) when the need to reconnect arises. A `return` is added after the recursion call.

**Comment by amjith** [comment]
I like it. 👍 

Thank you! Thank you! 🚀

**Comment by jialongl** [comment]
Glad that my quick hack worked in your framework.
Thanks for taking time to review and merge. :)

**Comment by amjith** [comment]
> Thanks for taking time to review and merge. :)

My pleasure. In fact, I made a couple of false starts on the reconnect issue, but my approaches were quite complicated and convoluted. So I'm glad you found a way to do this in a simple yet elegant manner.

**Pull request merged**
